### PR TITLE
feat: Erlang solution for problem001

### PR DESCRIPTION
**Pull request by machad0**

### CODE REVIEW

**Comment by ryukinix** [comment]
Thanks for the contrib!

**Comment by rafaelcn** [comment]
Albeit closed, I think we should enforce to contributors not put theirs names as a comment inside a file, it should be on the list of CONTRIBUTORS, the commit already confirms that he/they is/are the author(s) of the code.

**Comment by ryukinix** [comment]
I don't think this is a problem in general. Since seems pretty straightforward on local copy saw the author of code just opening the file. Otherwise, almost all my solutions have my name too, I'll not remove that. Is a lot. More than 100 files.

**Comment by ryukinix** [comment]
But I agreed that would be nice the contributors insert your own name on `SOLVERS.md`.

**Comment by machad0** [comment]
Ok, makes sense. On my next PR I'll update that `SOLVERS.md`

**Comment by ryukinix** [comment]
@machad0 thanks for the attention!

**Pull request merged**
