### PR TITLE
Add problems 85 | 87 | 97 | 104 solutions

### PR DESCRIPTION
**Pull request by A-Hilaly**
Add some solutions in Python and update SOLVERS.md

### CODE REVIEW

**Comment by ryukinix** [comment]
We have a typo on the last commit message. You can fix that?

Thanks for contributing, @A-Hilaly

**Comment by ryukinix** [comment]
That are hard problems, congratulations to solving it!

**Comment by A-Hilaly** [comment]
> We have a typo on the last commit message. You can fix that?
Sorry I don't see the typo is it in my PR ?

> That are hard problems, congratulations for solving it!
Thanks ! I must admit I have solved them many years ago I just try to do it again for the repo and refresh my math 📦 !

**Comment by ryukinix** [comment]
> Sorry I don't see the typo is it in my PR ?
image

**Comment by ryukinix** [comment]
In case if you are not familiar with git history rewrite, you can use `git rebase -i @~3` and select `reword` for the desired commit. So then, `git commit --amend` reedit the and call `git rebase --continue`.

**Comment by ryukinix** [comment]
I already fixed that @A-Hilaly! We're fine now.

**Comment by A-Hilaly** [comment]
It true I don't use git manipulation so often x( Thank you !

**Pull request merged**
