### PR TITLE
problem 2 elixir impl

### PR DESCRIPTION
**Pull request by leorog**

### CODE REVIEW

**Comment by ryukinix** [comment]
Thanks for this solution! We need just pass the tests.

**Comment by ryukinix** [comment]
You can rename your solution file from `solution.exs` to `solution_1.exs`, please? Is a pattern in the repository whose I would be glad if we can continue with it.

**Comment by rafaelcn** [comment]
LGTM.

**Comment by ryukinix** [comment]
Thanks. Now can be merged. 

BTW, great code in Elixir, @leorog. Very beautiful!

**Comment by leorog** [comment]
Thanks! 🎉

**Pull request merged**
