### PR TITLE
07 Elixir Alternative

### PR DESCRIPTION
**Pull request by leorog**
630 ~ 660 ms
cpu

### CODE REVIEW

**Comment by ryukinix** [comment]
@leorog please, read the rules now. I updated yesterday. Check here about PRs: [RULES.md](RULES.md)

**Comment by ryukinix** [comment]
Approved.

**Comment by lubien** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/DestructHub/ProjectEuler/pull-request/44/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=DestructHub/ProjectEuler)

**Comment by lubien** [comment]
Seems that both Elixir solutions for P007 are return the wrong value at the CI.

**Comment by ryukinix** [comment]
Why? Sucks. We need check that.

**Comment by ryukinix** [comment]
Rejected.

**Comment by leorog** [comment]
@ryukinix fixed, my bad

**Comment by ryukinix** [comment]
Approved.

**Pull request merged**
