### PR TITLE
[test] travis-ci build in Add/remove/update solutions case 

### PR DESCRIPTION
**Pull request by A-Hilaly**
Testing last added feature of travis-ci building solutions. See #137 #139 #142 #145 #146 #147

### CODE REVIEW

**Comment by A-Hilaly** [comment]
Yes ! I want to run more test to make sure we don't miss anything.

>@A-Hilaly A-Hilaly dismissed ryukinix’s stale review via 6d629e3 26 seconds ago

Does this proc because I pushed a new commit ?

**Comment by A-Hilaly** [comment]
@ryukinix Modifying problem002 in python wasn't builded

**Comment by ryukinix** [comment]
> @ryukinix Modified solution for problem002 in python wasn't builded

You look in the correct build commit? https://travis-ci.org/DestructHub/ProjectEuler/builds/303158169?utm_source=github_status&utm_medium=notification

**Comment by A-Hilaly** [comment]
I forgot to refresh the page x( so all fine for now !

**Comment by ryukinix** [comment]
> Does this proc because I pushed a new commit ?

New push invalidates old reviews, because bad code can be add from new commits, so we need review again since this happens.

**Comment by A-Hilaly** [comment]
```
Command: Files Build
Changed_core_files : 
 ['test']
```
this is not expected for removing a solution problem

**Comment by ryukinix** [comment]
> this is not expected for removing a solution problem

Actually this is expected for me. What should happens for you?

**Comment by ryukinix** [comment]
You call `chmod +x test` before on travis, this change the file mode, which git tracks as well.

**Comment by A-Hilaly** [comment]
> Actually this is expected for me. What should happens for you?

I expect this line in `stats.py` to print out that she skipped a solution 

```Python
if not os.path.exists(spath):
            sys.stdout.write("\rSkipped {}: file doesnt exist".format(spath))
            continue
```

**Comment by A-Hilaly** [comment]
@ryukinix it is coming from `filter_exists` in `test` file should I just remove the checking for path part in `stats.py`

**Comment by A-Hilaly** [comment]
```
Forced to exit: No solutions to build
Changed_core_files : 
 ['stats.py', 'test']
```

Much more better I think

**Comment by A-Hilaly** [comment]
```
0  Problem002       Go  0.334705  4613733    False
1  Problem002   Python  0.019369  4613732     True
...
Done. Your build exited with 0.
```

Do you agree with adding at the end of `build_solutions` a `sys.exit` if one of the solutions is wrong . Something like 
```
if have_wrong_solution(df):
        sys.exit("Wrong Solution(s)")
```

**Comment by ryukinix** [comment]
Yes, I'll implement that as well the time limit for 1min as described 
on our RULES.md.
This should be easy because the output is pandas DataFrame, so 
have_wrong_solution and have_exceeds_time_solution(df) should be pretty 
straightfoward. Can you fiil a issue about that?
-- 
As lembranças não são só do passado. Podem ser de agora e até de 
amanhã.
— Serial Experiments Lain
Manoel Vilela,
Discente em Engenharia da Computação,
Universidade Federal do Ceará.

**Comment by ryukinix** [comment]
> Forced to exit: No solutions to build
Changed_core_files : 
 ['stats.py', 'test']

Really better. I'll fill another PR and cherry pick this commit here to fix that, since this PR is just a complete mess (intentionally for test purposes).

**Comment by A-Hilaly** [comment]
> This should be easy because the output is pandas DataFrame

Yes I tried `True in df["Correct"]` seems to do the job 

 Can you fiil a issue about that?

Sure I will. I will close this PR

**Comment by ryukinix** [comment]
> Yes I tried True in df["Correct"] seems to do the job

As I said, pretty easy. Pandas is just too powerful.

**Pull request closed without merging**
