### PR TITLE
Remove mock/test solutions for differential build test

### PR DESCRIPTION
**Pull request by ryukinix**
Affects:

+ Problem300
+ Problem301

### CODE REVIEW

**Comment by A-Hilaly** [comment]
@ryukinix this case isn't discussed in what I have implemented (removing solutions ) thats why PR build is raising No such file or directory exception. 
I don't understand why 2 builds started up here

**Comment by ryukinix** [comment]
Yes, I understand. We need fix that. I'm merging that because we need remove this files, but we need fix that on `stats.py` and check the files before testing it, just use `os.path.exists` function and we are ok.

**Comment by ryukinix** [comment]
~Let's me see... maybe I can fix that easily.~
I fixed that, but now I have another problem. 

`python3 stats.py --build --files test` build all the tests, why?

**Comment by ryukinix** [comment]
There is two type of travis CI: Pull Requests and Push. Push event occurs when I do `git push` of a new branch of the repository like `remove-garbage` throught `git checkout -b cancer; git push -u origin cancer`. The pull request event occurs when I try merging that branch through the pull request: usually for me `hub pull-request`.

In general push events occurs first than PR, since we first make a new branch so then create a PR.

We need make some changes later about push events on Travis CI, because for now this is what we have:

image


We got this weird error.

**Comment by ryukinix** [comment]
@lubien `help --force --calling copycat-master`

**Comment by ryukinix** [comment]
I'm merging that, but we need fix that weird errors, ok @A-Hilaly ?

**Comment by A-Hilaly** [comment]
> python3 stats.py --build --files test build all the tests, why?

stats.py

at stats.py `handle_option()`
```Python
uncommited_solutions, uncommited_core_files = handle_files(options.files)
...
df = build_result(df[langs_selected],
                              options.all,
                              options.blame,
                              only=tbsolutions)
```

at `build_results`
```python
_problems = only if only else solutions_paths(df)
for lang, spath in _problems:
```

this is normal since when you deleted 2 problems and then just modified test, only which uncommitted_solutions is empty so _problems is becoming solutions_paths instead ( why causes to build all problems ). 
its true that it have lot of things fixed but #136 was merged too early, because there are many cases that aren't discussed that can make all build confusing

> I'm merging that, but we need fix that weird errors, ok @A-Hilaly ?

Yes sure we need to complete and secure #136

**Comment by ryukinix** [comment]
> its true that it have lot of things fixed but #136 was merged too early, because there are many cases that aren't discussed that can make all build confusing

Yes, my fault. Sorry.

**Comment by ryukinix** [comment]
> this is normal since when you deleted 2 problems and then just modified test, only which uncommitted_solutions is empty so _problems is becoming solutions_paths instead ( why causes to build all problems ).

I understand now. Is solution design. Thanks for explaining it. Thinking better maybe this behavior is a good thing. (maybe, I'm not sure)

**Comment by A-Hilaly** [comment]
> I understand now. Is solution design. Thanks for explaining it. Thinking better maybe this behavior is a good thing. (maybe, I'm not sure)

I know its a bit lego-ed x( , it needs also renaming of many things for better understanding. I will add some changes trying to fix the "lego" maybe this time we have a clearer way

**Pull request merged**
