### PR TITLE
Problem037: Create pe037.py

### PR DESCRIPTION
**Pull request by namannimmo10**
Another solution in python added

### CODE REVIEW

**Comment by namannimmo10** [comment]
> Thank you for your contributions ! Could you please rename your solution files to something like `solution_1.py` / `solution_2`etc... ? The `stats.py` only detect solutions following this naming standard

Sure, but some of the files are already there by that name

**Comment by A-Hilaly** [comment]
You can increment the solution number. It should just start with `solution_`, for example `solution_1.py` `solution_5.py` `solution_13.py` etc... 
when solutions are slow you can use something like `solution_slow_1.py`

**Comment by namannimmo10** [comment]
Okay!

**Comment by namannimmo10** [comment]
Check if the latest commit style is Okay?

**Comment by A-Hilaly** [comment]
I mean the python solution file, not the Pull Request title. In your branch you should rename the file name (for example rename `Problem037/Python/pe037.py` to `Problem037/Python/solution_2.py` ) . You'll have to recommit your changes and push again

**Comment by ryukinix** [comment]
> Check if the latest commit style is Okay?

Take as example this [PR] that you wrote. This style it's ok for us.

[PR]: https://github.com/DestructHub/ProjectEuler/pull/203

**Comment by ryukinix** [comment]
Another suggestion: try to fix the other PRs already open instead opening new ones.

**Pull request closed without merging**
