### PR TITLE
Solve 20 and 21 in Elixir

### PR DESCRIPTION
**Pull request by lubien**

### CODE REVIEW

**Comment by ryukinix** [comment]
We need rebase this branch, i can't do this because this branch is into your own repository. You can do this for me?

**Comment by lubien** [comment]
Done @ryukinix

**Comment by ryukinix** [comment]
:( sorry, we have a lot of PRs and I just see now your rebase. You can do this again? Sorry, thanks.

**Comment by lubien** [comment]
Done

Lain
>Waiting him for ask this again

**Comment by ryukinix** [comment]
:heart: lain card == green card :heart:

**Pull request merged**
