### PR TITLE
Solve 20 in Clojure (alternative solution)

### PR DESCRIPTION
**Pull request by leorog**

### CODE REVIEW

**Comment by tkovs** [comment]
It needs to send the result to the stdout 'cause the stats.ty checks the outputs. (I guess)

**Comment by ryukinix** [comment]
Yes, good point @tkovs. You can fix this, @leorog? Our program to do statistics of repository needs that pattern, just the answer on stdout.

**Comment by ryukinix** [comment]
I will clarify more the rules in soon. The readme I know are currently very messy.

**Comment by rafaelcn** [comment]
We need another rebase here, and we also need the way we work over this repository. Gonna plan things with Manoel soon.

**Comment by ryukinix** [comment]
Sorry, for some shit I need close this PR as closed #19. You can send a new branch with this commit on the repository instead a fork? Is more simple to mantaining and handle multiple merges. Thanks

**Pull request closed without merging**
