### PR TITLE
Solution 1 in O(1)

### PR DESCRIPTION
**Pull request by luizperes**
I know that we have numerous solutions for the `Problem 001`. However, this one is very beautiful and it is done in `O(1)` instead of `O(n)`.

The proof of the algorithm is below:
(Obs.: please check that the last considered number is `999` and not `1000`. That is to say, the first 3 lines should be: `floor(999/3)`, `floor(999/5)` and `floor(999/15)`)
proj_euler

### CODE REVIEW

**Comment by ryukinix** [comment]
AWESOMEEEE! Please add as well the picture as solution in Math/solution_1.png :)

**Comment by ryukinix** [comment]
The CI should failed, I didn't understand well as this passing, probably `test` script problem, but well:

```
Digest: sha256:f642c5e9ac8c6777d0d1f70e42a5524ca0834854b25a4c5efe8379f8e5163a32

Status: Downloaded newer image for destructhub/project_euler:latest

Command: Files Build

/usr/bin/ld:Problem001/C/Makefile: file format not recognized; treating as linker script

/usr/bin/ld:Problem001/C/Makefile:2: syntax error

collect2: error: ld returned 1 exit status

   (⣾) t: 0.01@Building next Problem001/C/Makefile:             <class 'OSError'>
```

You need fix problems on the Makefile.

**Comment by luizperes** [comment]
I will fix it :)

**Comment by luizperes** [comment]
How do we fix it @rafaelcn ? xD

**Comment by ryukinix** [comment]
Sorry about that, your solution and Makefile is completly right, but for some weird reason `stats.py` is trying compile the `Makefile` D:

**Pull request merged**
