### PR TITLE
Haskell 7% and Elixir 6.1%, soon enough there will be moar Elixir

### PR DESCRIPTION
**Pull request by lubien**

### CODE REVIEW

**Comment by ryukinix** [comment]
Great!

**Comment by rafaelcn** [comment]
LGTM

**Comment by ryukinix** [comment]
All destruction for us ~ 
lain-funny

**Comment by lubien** [comment]
captura de tela de 2016-09-01 23-33-08
Everything going well

**Comment by tkovs** [comment]
Challenge accepted.

**Comment by ryukinix** [comment]
@tkovs WOW

**Pull request merged**
