### PR TITLE
Solve 008 in Haskell

### PR DESCRIPTION
**Pull request by tkovs**

### CODE REVIEW

**Comment by rafaelcn** [comment]
Why is this commit still open? @tkovs can you please rebase your branch?

**Comment by ryukinix** [comment]
I updating without merge here. Is a little ugly but I don't has patience for now. And for some reason my ssh server are don't working here. WTF

**Comment by ryukinix** [comment]
WTF, almost 4 updates

**Comment by tkovs** [comment]
wtf

**Comment by tkovs** [comment]
merge --squash on master

**Comment by ryukinix** [comment]
@tkovs I updating this shit using github because i am having troubles with git on my notebook. Some random shit

**Comment by ryukinix** [comment]
@ryukinix Manoel Machado:
You can do just a simple git rebase master on this branch and send with "--force" to here?

**Comment by tkovs** [comment]
Merge

**Pull request merged**
