### PR TITLE
Add some hashes

### PR DESCRIPTION
**Pull request by lubien**

### CODE REVIEW

**Comment by lubien** [comment]
Approve

**Comment by rafaelcn** [comment]
Approved, don't merge this yet.

**Comment by ryukinix** [comment]
Why not, @rafaelcn? You'll add some hashs too?

**Comment by rafaelcn** [comment]
Because I would need to do another rebase, and that would be the third time doing it.

**Comment by lubien** [comment]
Since my PR with P012 .hash was already merged. Why not merge this one?

**Comment by ryukinix** [comment]
I will add with the milestone as you suggest before. I has some hashes here too, so I'll send a PR too.

**Pull request merged**
