### PR TITLE
Add problem 69 and 70 solutions 

### PR DESCRIPTION
**Pull request by A-Hilaly**
Added problem 69 and 70 solutions in python, md5 hashes and readme

### CODE REVIEW

**Comment by ryukinix** [comment]
Awesome! Exactly how the rules is expected.

Just one question, you used the `add` script on the repo to add hash and README.md or just created manually?

**Comment by ryukinix** [comment]
Well, answer me that later. I'll merge this since is just ok

**Comment by A-Hilaly** [comment]
I created them manually. I just realized the add script exists

**Comment by A-Hilaly** [comment]
is md5sum (in add script) a function or just an alias to coreutils md5 ?

**Comment by ryukinix** [comment]
> I created them manually. I just realized the add script exists

Fine. Just to you know, we have a little bug here. [`stats.py`] assume that the answer hash was computed with a new-line  on the end because on [`add`] script was wrongly wrote with an `echo` function which append a newline on the output. So in another words, If we will try test your solutions will fails without no reason because the digested hash will always append a newline because this bug. I know is bad :/ sorry for this. We would be nice in future we regenerate the hash done right or make `stats.py` compute two hashs if the first comparison fails (just a ideia).

Is the binary `md5sum` presented on coreutils.

[`add`]: https://github.com/DestructHub/ProjectEuler/blob/1503bae21e7d2c2575b1fdd3b6a0f21946b0271b/add#L13
[`stats.py`]: https://github.com/DestructHub/ProjectEuler/blob/1503bae21e7d2c2575b1fdd3b6a0f21946b0271b/stats.py#L316

> is md5sum (in add script) a function or just an alias to coreutils md5 ?

`md5sum` binary is present on `coreutils` package at least on my Linux distro (Arch Linux).

**Comment by A-Hilaly** [comment]
`./add `script is working fine for me (when I change `md5sum` to `md5)`, the output .hash file is something like

hashop

>  the answer hash was computed with a new-line on the end

i remarked that all the other problems hash files contain a  ' - ' at the end, which is treated by stats.py in `read_hashfile(fpath)` and the hashes I added don't have them. but I think this is not a problem for stats.py since it uses `str.strip`

if I understand what the real problem, you mean why is there a second line in the file ? in this case that is totally normal and not echo's function.

ophash-

`digest_answer` and `read_hashfiles` uses multiple manipulations using '\n' char on open().read() output then try to get hash value by  , why not just use open().readlines() and take first element, so just treat hash file as single line? (you'll still have a "\n" but thats normal )

> We would be nice in future we regenerate the hash done right or make stats.py compute two hashs if the first comparison fails (just a ideia).

if this is really a bug just open an issue so we can discuss how to fix this.

**Comment by ryukinix** [comment]
> edit: I started thinking that you are maybe hashing the solution + '\n' ( at digest_answer ) but still don't get why not just the take the hash value simply


Yes, I'm doing that. This is what happened on `add` script `(echo $answer | md5sum)`. All hash values from `add` put a additional `\n` on answer because I use `echo | md5sum`. The problem is not the `.hash` file, if has a newline or not, but the answer which genereates the hash. Since almost all the hash calculated on this repo was made using the `add` script, all the hashes was calculated as `<answer>\n` -> `md5sum`. Because all the files have a `\n` on precalculated `hash`, on `digest_answer` i need to append a `\n` on answer even if doesn't exists :/.

Let's say. If the answer is `2426`, the hash was generated as `2426\n`. So when I regenerate to check on `digest_answer` I need to ensure that a new line is on the end. You got that? 

Sorry for this confusion, is so much unnecessary mess. If I just take the hash value from the answer (without treat the newline shit) on `stats.py` all the hashs will calculated wrongly and the answers will be invalid (for now). :(

To fix that, as I say, we'll need fix two things basically:

1. Translate that [line] to `$(printf $2 | md5sum)`
2. Regenerate all the hashs with that script again.

On (2) we can use the `stats.py` to fetch the correctly answers and use them to regenerate. 

Sorry if this is still confusing, but I hope that it make more clear what I'm trying to say, 

[line]: https://github.com/DestructHub/ProjectEuler/blob/1503bae21e7d2c2575b1fdd3b6a0f21946b0271b/add#L13

**Comment by A-Hilaly** [comment]
I understand whats happening now !
> You got that?

100%

Ill make a PR fixing this soon

**Comment by ryukinix** [comment]
I'll be so glad! Thank you for supporting us.

**Pull request merged**
