### PR TITLE
this solution was wrong

### PR DESCRIPTION
**Pull request by vidalvasconcelos**

### CODE REVIEW

**Comment by vidalvasconcelos** [comment]
This solution was mine, but  others solutions are wrong too, how is the policy for refact the wrong solutions?

**Comment by rafaelcn** [comment]
You'd just need to send us the correct version of the problem and we would rebase and merge it.

**Comment by vidalvasconcelos** [comment]
Thanks @rafaelcn!

**Comment by rafaelcn** [comment]
Not a problem @vidalvasconcelos!

**Pull request merged**
