### PR TITLE
Minor bug fix and implementation in other 3 new languages

### PR DESCRIPTION
**Pull request by luizperes**

### CODE REVIEW

**Comment by ryukinix** [comment]
Looks good me for, approved.

**Comment by tkovs** [comment]
Well done.

**Comment by ryukinix** [comment]
@tkovs We need a solution for Problem038! If you do that, the first 40 problems are done!

**Comment by ryukinix** [comment]
You was invited to join us!

**Comment by tkovs** [comment]
I'm already a member, but the Problem038... I couldn't solve myself.

**Comment by ryukinix** [comment]
I'll keep on the README a section whose points the "NEXT GOAL", one problem descriptive which the group are focusing.

**Comment by luizperes** [comment]
@tkovs Problem038 is solved in two different ways from yesterday :)

**Comment by ryukinix** [comment]
YEEEs, thanks for the Swift solution, @luizperes! Go on to finish the 40~50 ?! HAHAHA My next aim is the 41.

**Pull request merged**
