### PR TITLE
Solve 008 in clojure

### PR DESCRIPTION
**Pull request by leorog**

### CODE REVIEW

**Comment by rafaelcn** [comment]
Greak, keep the awesome work! :+1:

**Comment by rafaelcn** [comment]
Could you please do a `git pull origin master --rebase` on your branch? This way we can merge without worries.

**Comment by ryukinix** [comment]
Would be great, @leorog! Thanks. Just a little rebase to avoid all the chaos of merge not-fastfoward

**Comment by leorog** [comment]
Rebase produces "branch up to date", is this right?

**Comment by rafaelcn** [comment]
It actually overwrite your history. It updates your tree and place your last work on top (HEAD) of the tree.

**Comment by rafaelcn** [comment]
Sorry about that, you will have to re-do a rebase, we've just merged a PR.

**Comment by rafaelcn** [comment]
LGTM.

**Pull request merged**
