### PR TITLE
Solve 003 in Clojure

### PR DESCRIPTION
**Pull request by leorog**
Some suggestion to improve? (code & performance)

performance

### CODE REVIEW

**Comment by leorog** [comment]
I will remake this problem.

**Comment by ryukinix** [comment]
Good question. I will made a revision in soon. You can send the next PRs as member of repository, @leorog? If you send a branch is more easily because we can work together in the same PR. This can be usefull with code review and other tasks like rebase.

Thanks. You already member of Solvers team.

**Comment by leorog** [comment]
wow, thanks ;)

giphy

**Comment by ryukinix** [comment]
captura de tela_2016-09-04_14-42-54

**Comment by leorog** [comment]
So, changing the _prime?_ algorithm to 

``` Clojure 
(defn prime? [n]
    (= 1 (->> (range 1 (inc (Math/sqrt n)))
            (map (partial rem n))
            (filter (partial = 0))
            (count))))
```

increased the computation time from 6s ~ 7s to 22s ~ 27s. I will try to improve this in future but for now I will keep this solution as is.

**Comment by ryukinix** [comment]
I can't merge this because the origin repository was deleted.

**Comment by ryukinix** [comment]
I'll close.

**Pull request closed without merging**
