### PR TITLE
Add my name to the table

### PR DESCRIPTION
**Pull request by rafaelcn**
Signed-off-by: Rafael Campos Nunes <rafaelnunes@engineer.com>

### CODE REVIEW

**Comment by rafaelcn** [comment]
Need your approve over here @ryukinix

**Comment by lubien** [comment]
Approved

**Comment by rafaelcn** [comment]
Thanks, we still need something to not use CI if it isn't needed.

**Comment by lubien** [comment]
@ryukinix said once about the possibility of checking modifications on `solution_*` files and running just then.

**Comment by rafaelcn** [comment]
Yes, we have to look on it later.

**Pull request merged**
