### PR TITLE
Solve 029 in Haskell

### PR DESCRIPTION
**Pull request by tkovs**

### CODE REVIEW

**Comment by rafaelcn** [comment]
It seems that you will have some problems trying to overcome the quantity of solutions in haskell @lubien :smile:

**Comment by lubien** [comment]
@rafaelcn
Now I understand that first I need to kill haskellers then I can make solutions.

**Comment by rafaelcn** [comment]
Hahaha, I'll be in the background in case you both try to kill each other.

**Comment by tkovs** [comment]
Keep calm, I'm slowly recently.

**Pull request merged**
